from django.urls import path

from .analysis_areas import AnalysisAreaHistoryView
from .map_views import (
    MapContextView,
    MapGeocodeView,
    MapHotspotsView,
    MapLayerView,
    MapPointSampleView,
    MapReverseGeocodeView,
    MapRouteView,
)
from .views import (
    AdminBoundariesView,
    AdminBoundaryDetailView,
    DashboardOverviewView,
    DashboardTimeseriesView,
    LocationDetailView,
    LocationsView,
    NdviMonthlyView,
    NdviRangeView,
    NdviYearlyView,
    RainfallCompareLocationsView,
    RainfallComparePeriodsView,
    RainfallMonthlyView,
    RainfallRangeView,
    RainfallYearlyView,
    SoilMoistureMonthlyView,
    SoilMoistureRangeView,
    StandardProvincesView,
    StandardWardsView,
    TemperatureMonthlyView,
    TemperatureRangeView,
    TvdiDroughtSummaryView,
    TvdiMonthlyView,
    TvdiRangeView,
    TvdiSevereEventsView,
)


urlpatterns = [
    path("analysis-areas/history", AnalysisAreaHistoryView.as_view()),
    path("boundaries", AdminBoundariesView.as_view()),
    path("boundaries/<int:admin_level>/<str:boundary_code>", AdminBoundaryDetailView.as_view()),
    path("standard/provinces", StandardProvincesView.as_view()),
    path("standard/wards", StandardWardsView.as_view()),
    path("locations", LocationsView.as_view()),
    path("locations/<int:location_id>", LocationDetailView.as_view()),
    path("map/geocode", MapGeocodeView.as_view()),
    path("map/reverse", MapReverseGeocodeView.as_view()),
    path("map/context", MapContextView.as_view()),
    path("map/route", MapRouteView.as_view()),
    path("map/layer", MapLayerView.as_view()),
    path("map/point-sample", MapPointSampleView.as_view()),
    path("map/hotspots", MapHotspotsView.as_view()),
    path("rainfall", RainfallRangeView.as_view()),
    path("rainfall/monthly", RainfallMonthlyView.as_view()),
    path("rainfall/yearly", RainfallYearlyView.as_view()),
    path("rainfall/compare-periods", RainfallComparePeriodsView.as_view()),
    path("rainfall/compare-locations", RainfallCompareLocationsView.as_view()),
    path("temperature", TemperatureRangeView.as_view()),
    path("temperature/monthly", TemperatureMonthlyView.as_view()),
    path("soil-moisture", SoilMoistureRangeView.as_view()),
    path("soil-moisture/monthly", SoilMoistureMonthlyView.as_view()),
    path("ndvi", NdviRangeView.as_view()),
    path("ndvi/monthly", NdviMonthlyView.as_view()),
    path("ndvi/yearly", NdviYearlyView.as_view()),
    path("tvdi", TvdiRangeView.as_view()),
    path("tvdi/monthly", TvdiMonthlyView.as_view()),
    path("tvdi/drought-summary", TvdiDroughtSummaryView.as_view()),
    path("tvdi/severe-events", TvdiSevereEventsView.as_view()),
    path("dashboard/overview", DashboardOverviewView.as_view()),
    path("dashboard/timeseries", DashboardTimeseriesView.as_view()),
]
